[build]
  base = "client/"
  publish = "./"
  command = "# No build command needed"

[dev]
  framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' ws: wss: *; media-src 'self' blob:"
